spiderkeeper/main/views.py
# -*- coding: utf-8 -*-
import pymongo
import redis
import json
import requests

from .conf import conf

from datetime import datetime
from collections import OrderedDict
from peewee import *

from flask import render_template, redirect, url_for, flash, make_response, jsonify, request

from flask import Blueprint
from . import basic_auth

from .settings import SERVERS, REDIS_CONFIG, COUNTRYS

main = Blueprint('main', __name__)


def select_config(port, db):
    return 'redis://:%(passwd)s@%(host)s:%(port)s/%(db)s' % \
                                {
                                    'passwd': REDIS_CONFIG['passwd'],
                                    'host': REDIS_CONFIG['host'],
                                    'port': REDIS_CONFIG['port'][port],
                                    'db': REDIS_CONFIG['db'][db]
                                }

r = redis.StrictRedis.from_url(select_config(0, 0))
r2 = redis.StrictRedis.from_url(select_config(-1, -1))
r3 = redis.StrictRedis.from_url(select_config(0, 1))

RDS_DICT = OrderedDict([
    (u'挖矿', {'name': r, 'ip': REDIS_CONFIG['host'], 'port': REDIS_CONFIG['port'][0], 'db': REDIS_CONFIG['db'][0]}),
    (u'销参', {'name': r2, 'ip': REDIS_CONFIG['host'], 'port': REDIS_CONFIG['port'][1], 'db': REDIS_CONFIG['db'][1]}),
    (u'Ebay', {'name': r3, 'ip': REDIS_CONFIG['host'], 'port': REDIS_CONFIG['port'][0], 'db': REDIS_CONFIG['db'][2]})
])


SPIDERS = {}
SERVERS = OrderedDict(SERVERS)


@main.route('/logs/<server>', methods=['GET', 'POST'])
def logs(server):
    url = 'http://' + SERVERS[server]['ip'] + ':6800/logs/'
    return render_template('scrapyd_log.html', url=url)


@main.route('/logs/<server>/<project>/<spider>/<sid>', methods=['GET', 'POST'])
def spider_log(server, project, spider, sid):
    url = 'http://' + SERVERS[server]['ip'] + ':6800/logs/' + project + '/' + spider + '/' + sid + '.log'
    return render_template('scrapyd_log.html', url=url)


@main.route('/listqueue/<server>', methods=['GET', 'POST'])
def listqueue(server):
    queue = OrderedDict()
    queue_format = OrderedDict()
    r_ = RDS_DICT[server]['name']
    keys_list = r_.keys()
    for keys in keys_list:
        try:
            ret = r_.zcard(keys.decode())
        except Exception as e:
            pass
        else:
            queue[keys.decode()] = ret

    queues = sorted(queue.items(), key=lambda x: x[0], reverse=True)
    dup = set()
    countrys = ['BiHu', 'WeChat', 'Flash_Xcong', 'Flash_Jinse', 'Flash_BiShiJie',
                'Flash_Imeos', 'Flash_Chainnews', 'Flash_Odaily']
    for q in queues:
        index = q[0].rfind('_')
        q_key = q[0][:index]
        if q_key not in dup:
            dup.add(q_key)
        queue_num = q[1]
        country = q[0].split(':')[0][index+1:]
        if not queue_format.get(q_key):
            queue_format[q_key] = {}
        queue_format[q_key][country] = queue_num
    return render_template('listqueue.html', countrys=countrys, queue=queue_format, server=server)


@main.route('/rediss', methods=['GET', 'POST'])
def rediss():
    redis_num = OrderedDict()
    index = 0
    for item in RDS_DICT:
        queue_set = set()
        index += 1
        rds_lst = RDS_DICT[item]['name'].keys()
        [queue_set.add(queue[:queue.rfind('_')]) for queue in rds_lst]
        if 'mysql' in queue_set:
            queue_set.remove('mysql')
        if 'mysql_lock' in rds_lst:
            rds_lst.remove('mysql_lock')
        redis_num[item] = RDS_DICT[item]
        redis_num[item]['num'] = len(rds_lst)
        redis_num[item]['index'] = index
        redis_num[item]['queue_num'] = len(queue_set)
    return render_template('redis_dashboard.html', redis_num=redis_num)


@main.route('/', methods=['GET', 'POST'])
@basic_auth.required
def index():
    running = OrderedDict()
    logs_num = OrderedDict()
    index = 0
    for server in SERVERS:
        try:
            info_json = requests.get('http://{0}:6800/daemonstatus.json'.format(SERVERS[server]['ip']), timeout=5).json()
            info_json['index'] = index
            running[server] = info_json
            logs_num[server] = {'ip': SERVERS[server]['ip'], 'status': 'active'}
            index += 1
        except Exception as e:
            running[server] = 'bad'
            logs_num[server] = {'ip': SERVERS[server]['ip'], 'status': 'bad', 'index': index}
    return render_template('job_dashboard.html', running=running, logs_num=logs_num)


@main.route('/listprojects/<server>')
def listprojects(server):
    f = requests.get('http://{0}:6800/listprojects.json'.format(SERVERS[server]['ip'])).json()
    projects = f['projects']

    projects_ebay, projects_wk, projects_xc = [[] for _ in range(3)]
    for pro in projects:
        if pro.startswith('ebay'):
            projects_ebay.append(pro)
        elif (pro.startswith('xc')) or (pro in ['keywordad', 'reviewfp']):
            projects_xc.append(pro)
        else:
            projects_wk.append(pro)

    running_ebay, running_wk, running_xc = [OrderedDict() for _ in range(3)]
    runnings = [(u'销参', running_xc), (u'ebay', running_ebay), (u'挖矿', running_wk)]
    for index, projects in enumerate([projects_xc, projects_ebay, projects_wk]):
        running = runnings[index][1]
        index = 0
        for project in projects:
            if not running.get(project, None):
                running[project] = {}
            jobs_info = requests.get('http://{0}:6800/listjobs.json?project={1}'.format(SERVERS[server]['ip'], project)).json()
            if not SPIDERS.get(server):
                SPIDERS[server] = {}
            if not SPIDERS[server].get(project):
                spider = len(requests.get('http://{0}:6800/listspiders.json?project={1}'.format(SERVERS[server]['ip'], project)).json()['spiders'])
                SPIDERS[server][project] = spider

            index += 1
            running[project]['index'] = index
            running[project]['spider'] = SPIDERS[server][project]
            for key, value in jobs_info.items():
                if isinstance(value, (str, unicode)):
                    running[project][key] = value
                else:
                    running[project][key] = len(value)

    return render_template('listprojects.html', server=server, runnings=OrderedDict(runnings), countrys=COUNTRYS)


@main.route('/projectstatus/<server>/<project>')
def projectstatus(server, project):
    projectstatus = requests.get('http://{0}:6800/listjobs.json?project={1}'.format(SERVERS[server]['ip'], project)).json()
    runnings, finisheds, pendings = [projectstatus[key] for key in list(projectstatus.keys())[1: 4]]
    for status_lst in [runnings, finisheds, pendings]:
        index = 0
        if status_lst:
            for ind, item_dic in enumerate(status_lst):
                item_dic_cp = item_dic
                if item_dic.get('end_time'):
                    fend_time = datetime.strptime(item_dic['end_time'].split('.')[0], '%Y-%m-%d %H:%M:%S')
                    fstart_time = datetime.strptime(item_dic['start_time'].split('.')[0], '%Y-%m-%d %H:%M:%S')
                    cost_time = str(fend_time - fstart_time)
                    item_dic['end_time'] = item_dic['end_time'].split('.')[0]
                    if cost_time == "0:00:01":
                        # print(item_dic)
                        status_lst.remove(item_dic_cp)
                    item_dic['cost_time'] = cost_time
                item_dic['index'] = index
                index += 1
                if item_dic.get('start_time'):
                    item_dic['start_time'] = item_dic['start_time'].split('.')[0]

    status_infos = {u'正在运行': runnings, u'已结束': finisheds, u'等待中': pendings}
    # return jsonify(status_infos)
    return render_template('projectstatus.html', status_infos=status_infos, server=server, project=project, countrys=COUNTRYS)


@main.route('/schedule/<server>/<project>/<spider>')
def schedule(server, project, spider):
    params = {'project': project, 'spider': spider}
    f = requests.post('http://{0}:6800/schedule.json'.format(SERVERS[server]['ip']), params=params)
    return f.content


@main.route('/create/<server>', methods=['GET', 'POST'])
def create(server):
    if request.method == "POST":
        project = request.form.get('project')
        spider = request.form.get('country')
        params = {'project': project, 'spider': spider}
        try:
            requests.post('http://{0}:6800/schedule.json'.format(SERVERS[server]['ip']), params=params)
            flash(u'启动 {0} 爬虫成功'.format(project))
        except:
            flash(u'启动 {0} 失败'.format(project))
    return redirect(url_for('main.listprojects', server=server))


@main.route('/cancel/<server>/<project>/<id>')
def cancel(server, project, id):
    params = {'project': project, 'job': id}
    try:
        res = requests.post('http://{0}:6800/cancel.json'.format(SERVERS[server]['ip']), params=params)
        flash(u'关闭 {0} 爬虫成功'.format(project))
    except:
        flash(u'关闭 {0} 爬虫失败'.format(project))
    return redirect(url_for('main.projectstatus', server=server, project=project))


@main.route('/force_cancel/<server>/<project>/<id>')
def force_cancel(server, project, id):
    params = {'project': project, 'job': id}
    try:
        for _ in range(2):
            requests.post('http://{0}:6800/cancel.json'.format(SERVERS[server]['ip']), params=params)
        flash(u'强制关闭 {0} 爬虫成功'.format(project))
    except:
        flash(u'强制关闭 {0} 爬虫失败'.format(project))
    return redirect(url_for('main.projectstatus', server=server, project=project))


@main.route('/close/<server>/<project>')
def close(server, project):
    f = requests.get('http://{0}:6800/listjobs.json?project={1}'.format(SERVERS[server]['ip'], project)).json()
    jobs = f['running']

    count = 0
    for job in jobs:
        params = {'project': project, 'job': job['id']}
        f = requests.post('http://{0}:6800/cancel.json'.format(SERVERS[server]['ip']), params=params).json()
        reply = f

spiderkeeper/main/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SpiderKeeper</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/static/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/static/css/skins/skin-black-light.min.css">
    <!--custom css-->
    <link rel="stylesheet" href="/static/css/app.css">
    <link rel="stylesheet" href="/static/css/define.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="/static/js/html5shiv.min.js"></script>
    <script src="/static/js/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-black-light sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <a href="/" class="logo">
            <span class="logo-mini"><b>S</b>K</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Spider</b>Keeper</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->

            <ul class="nav navbar-nav nav-xs">
                <li style="width: 50px;float: left;">
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                </li>
                <li class="dropdown" style="float: left;">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                       style="padding-top: 15px;padding-bottom: 15px;">
                        <span>Projects</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- {% for project in project_list %} -->
                        <!-- <li><a href="/project/{{ project.id }}">{{ project.project_name }}</a></li> -->
                        <!-- {% endfor %} -->
                        <li role="separator" class="divider"></li>
                        <li><a href="#" data-toggle="modal" data-target="#project-create-modal">Create Project</a>
                        </li>
                    </ul>
                </li>
            </ul>

        </nav>
    </header>

    <!-- =============================================== -->

    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <div style="position: relative;width: 100%;padding: 10px;overflow: hidden;height: 35px;">
                <div style="padding: 5px 5px 5px 15px;line-height: 1;position: absolute;left: 65px;">
                    <p><b>陀螺采集系统</b></p>
                </div>
            </div>
            <ul class="sidebar-menu">
<!--                 <li class="header">JOBS</li>
                <li><a href=""><i
                        class="fa fa-dashboard text-blue"></i>
                    <span>Dashboard</span></a></li>
                <li><a href=""><i class="fa fa-tasks text-green"></i>
                        <span>Periodic Jobs</span></a></li>
                    <li class="header">SPIDERS</li>
                    <li><a href=""><i class="fa fa-flask text-red"></i>
                        <span>Dashboard</span></a>
                    </li>
                    <li><a href=""><i class="fa fa-server text-orange"></i>
                        <span>Deploy</span></a></li>
                    <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Settings</span></a></li>
                    <li class="header">PROJECT</li>
                    <li><a href=""><i class="fa  fa-area-chart text-gray"></i> <span>Running Stats</span></a>
                    </li>
                    <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Members</span></a></li>
                    <li><a href=""><i class="fa fa-gears text-red"></i> <span>Manage</span></a></li> -->
                    <li class="header">SERVER</li>
                    <li><a href="/"><i class="fa fa-bolt text-red"></i> <span>Spider Server</span></a>
                    <li><a href="{{ url_for('main.rediss') }}"><i class="fa fa-tasks text-green"></i> <span>Redis Server</span></a>
                </li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- =============================================== -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            {% block content_header %}{% endblock %}
        </section>

        <!-- Main content -->
        <section class="content">
            {% for message in get_flashed_messages() %}
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}

            {% block content_body %}
            {% endblock %}
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 1.0.1
        </div>
        <strong><a href="/">SpiderKeeper</a>.</strong>
    </footer>


    <!-- /.modal -->
</div>
<!-- ./wrapper -->
<script src="/static/js/popper.min.js"></script>
<!-- jQuery 2.2.3 -->
<script src="/static/js/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="/static/js/bootstrap.min.js"></script>
<!-- SlimScroll -->
<script src="/static/js/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/static/js/fastclick.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/js/AdminLTE.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/static/js/demo.js"></script>

{% block script %}{% endblock %}
</body>
</html>

spiderkeeper/main/templates/listprojects.html
{% extends "base.html" %}
{% block content_header %}


<h1>{{ server }} Dashboard</h1>
<ol style="float: right;
    margin-top: 0;
    margin-bottom: 0;
    font-size: 12px;
    padding: 7px 5px;
    position: absolute;
    top: 15px;
    right: 10px;">
    <button type="button" class="btn btn-success btn-flat" style="margin-top: -10px;" data-toggle="modal"
            data-target="#job-run-modal">RunOnce
    </button>
</ol>
{% endblock %}
{% block content_body %}


{% for spider in runnings %}
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">{{ spider }} Running Jobs</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body table-responsive">
            <table class="table table-striped">
                <tr>
                    <th style="width: 30px">index</th>
                    <th style="width: 80px">project</th>
                    <th style="width: 160px">spiders <span class="fenge">|</span> handler</th>
                    <th style="width: 160px">running <span class="fenge">|</span> handler</th>
                    <th style="width: 100px">finished</th>
                    <th style="width: 100px">pending</th>
                    <th style="width: 100px">status</th>
                    <th style="width: 100px">node_name</th>
                </tr>
                {% for project in runnings[spider]%}
                <tr>
                    <td>{{ runnings[spider][project]['index'] }}</td>
                    {% if runnings[spider][project]['running'] > 0 or runnings[spider][project]['finished'] > 0 or runnings[spider][project]['pending'] > 0 %}
                    <td><a href="{{ url_for('main.projectstatus', server=server, project=project) }}">{{ project }}</a></td>
                    {% else %}
                    <td>{{ project }}</td>
                    {% endif %}

                    <td>
                        <a href=""  class="label label-warning" data-toggle="tooltip" data-placement="left" title="爬虫数量">{{ runnings[spider][project]['spider'] }}</a> <span class="fenge">|</span>
                        <a href="{{ url_for('main.start', server=server, project=project) }}">Run All</a>
                    </td>

                    {% if runnings[spider][project]['running'] > 0 %}
                    <td>
                        <span data-toggle="tooltip" data-placement="left" title="正在运行" class="label label-success">
                        {{ runnings[spider][project]['running'] }}</span>
                        <span class="fenge">|</span>
                        <a href="{{ url_for('main.close', server=server, project=project) }}">Close All</a>
                    </td>
                    {% else %}
                    <td><span class="">{{ runnings[spider][project]['running'] }}</span></td>
                    {% endif %}

                    {% if runnings[spider][project]['finished'] > 0 %}
                    <td class="" data-toggle="tooltip" data-placement="left" title="已完成任务"><span class="label label-danger">{{ runnings[spider][project]['finished'] }}</span></td>
                    {% else %}
                    <td>{{ runnings[spider][project]['finished'] }}</td>
                    {% endif %}

                    {% if runnings[spider][project]['pending'] > 0 %}
                    <td class="" data-toggle="tooltip" data-placement="left" title='即将运行爬虫数量'><span class="label label-info">{{ runnings[spider][project]['pending'] }}</span></td>
                    {% else %}
                    <td><span>{{ runnings[spider][project]['pending'] }}</span></td>
                    {% endif %}

                    <td><span class="label label-default">{{ runnings[spider][project]['status'] }}</span></td>
                    <td>{{ runnings[spider][project]['node_name'] }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endfor %}



<div class="modal fade" role="dialog" id="job-run-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ url_for('main.create', server=server) }}" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Run Spider Once</h4>
                </div>


                <div class="modal-body">
                    <div class="form-group">
                        <label>Spider</label>
                        <select class="form-control" name="spider_name">
                            {% for spider in runnings %}
                            {% for server in runnings[spider] %}
                            <option value="{{ spider.spider_name }}">{{ server }}</option>
                            {% endfor %}
                            {% endfor %}
                        </select>
                    </div>


                    <div class="form-group">
                        <label>Country</label>
                        <select class="form-control" name="priority">
                            {% for enc, cnc in countrys.items() %}
                            <option value="{{ enc }}">{{ cnc }}</option>
                            {% endfor %}
                        </select>
                    </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
{% endblock %}

spiderkeeper/main/templates/listqueue.html
{% extends "base.html" %}
{% block content_header %}


<h1>{{ server }} Queue Dashboard</h1>

{% endblock %}


{% block content_body %}



{% for q in queue %}
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">{{ q }}</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body table-responsive">
            <table class="table table-striped">
                <tr>
                    {% for c in countrys %}
                    <th style="width: 40px">{{ c }}</th>
                    {% endfor %}
                </tr>
                <tr>
                    {% for c in countrys %}
                        {% if queue[q].get(c, 0) == 0 %}
                        <td><span class=""> - </span></td>
                        {% elif queue[q].get(c, 0) < 1000 %}
                        <td><span class="label label-info">{{ queue[q].get(c, 0) }}</span></td>
                        {% elif queue[q].get(c, 0) < 10000 %}
                        <td><span class="label label-warning">{{ queue[q].get(c, 0) }}</span></td>
                        {% elif queue[q].get(c, 0) < 100000 %}
                        <td><span class="label label-danger">{{ queue[q].get(c, 0) }}</span></td>
                        {% else %}
                        <td><span class="label label-success">{{ queue[q].get(c, 0) }}</span></td>
                        {% endif %}
                    {% endfor%}
                </tr>
            </table>
        </div>
    </div>
{% endfor %}

<script type="text/javascript">
    
    var ref_flag;
    var auto_time = 1;
    window.clearInterval(ref_flag);
    ref_flag = window.setInterval(function(){
        window.location.reload();
    }, auto_time * 5000);

</script>



{% endblock %}

spiderkeeper/main/templates/projectstatus.html
{% extends "base.html" %}
{% block content_header %}


<h1>{{ project }} Job Dashboard</h1>
<ol style="float: right;
    margin-top: 0;
    margin-bottom: 0;
    font-size: 12px;
    padding: 7px 5px;
    position: absolute;
    top: 15px;
    right: 10px;">
    <button type="button" class="btn btn-success btn-flat" style="margin-top: -10px;" data-toggle="modal"
            data-target="#job-run-modal">RunOnce
    </button>
</ol>
{% endblock %}


{% block content_body %}



{% for status in status_infos %}
{% if status_infos[status] | length > 0 %}
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">{{ status }}</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body table-responsive">
            <table class="table table-striped">
                {% if status_infos[status] | length > 0 %}
                {% if status_infos[status][0].get('pid') %}
                <tr>
                    <th style="width: 100px">index</th>
                    <th style="width: 160px">spider</th>
                    <th style="width: 100px">start_time</th>
                    <th style="width: 100px">pid</th>
                    <th style="width: 160px">id</th>
                    <th style="width: 100px">control</th>
                </tr>
                {% for dic in status_infos[status] %}
                <tr>
                    <td><span class="">{{ dic['index'] }}</span></td>
                    <td>
                        <span class="">
                            <a href="{{ url_for('main.spider_log', server=server, project=project, spider=dic['spider'], sid=dic['id']) }}">
                            {{ dic['spider'] }}</a>
                        </span>
                    </td>
                    <td><span class="">{{ dic['start_time'] }}</span></td>
                    <td><span class="">{{ dic['pid'] }}</span></td>
                    <td><span class="">{{ dic['id'] }}</span></td>
                    <td>
                        <a href="{{ url_for('main.cancel', server=server, project=project, id=dic['id']) }}">
                        <button type="button" class="btn btn-info btn-sm">
                            end
                        </button> 
                        </a>
                        <span class="fenge">|</span>
                        <a href="{{ url_for('main.force_cancel', server=server, project=project, id=dic['id']) }}">
                        <button type="button" class="btn btn-outline-danger btn-sm">
                            forced end
                        </button>
                        </a>
                    </td>
                </tr>
                {% endfor %}

                {% elif status_infos[status][0].get('end_time') %}
                <tr>
                    <th style="width: 100px">index</th>
                    <th style="width: 160px">spider</th>
                    <th style="width: 100px">start_time</th>
                    <th style="width: 100px">end_time</th>
                    <th style="width: 100px">cost_time</th>
                    <th style="width: 160px">id</th>
                </tr>
                {% for dic in status_infos[status] %}
                <tr>
                    <td><span class="">{{ dic['index'] }}</span></td>
                    <td>
                        <span class="">
                            <a href="{{ url_for('main.spider_log', server=server, project=project, spider=dic['spider'], sid=dic['id']) }}">
                            {{ dic['spider'] }}</a>
                        </span>
                    </td>
                    <td><span class="">{{ dic['start_time'] }}</span></td>
                    <td><span class="">{{ dic['end_time'] }}</span></td>
                    <td><span class="">{{ dic['cost_time'] }}</span></td>
                    <td><span class="">{{ dic['id'] }}</span></td>
                </tr>
                {% endfor %}

                {% else %}
                <tr>
                    <th style="width: 100px">index</th>
                    <th style="width: 160px">spider</th>
                    <th style="width: 160px">id</th>
                </tr>
                {% for dic in status_infos[status] %}
                <tr>
                    <td><span class="">{{ dic['index'] }}</span></td>
                    <td><span class="">{{ dic['spider'] }}</span></td>
                    <td><span class="">{{ dic['id'] }}</span></td>
                </tr>
                {% endfor %}
                {% endif %}
                {% endif %}
            </table>
        </div>
    </div>
{% endif %}
{% endfor %}






<div class="modal fade" role="dialog" id="job-run-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ url_for('main.create', server=server) }}" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Run Spider Once</h4>
                </div>

                <div class="modal-body">
                    <div class="form-group">
                        <label>Spider</label>
                        <select class="form-control" name="spider_name">
                            <option value="{{ project }}">{{ project }}</option>
                        </select>
                    </div>


                    <div class="form-group">
                        <label>Country</label>
                        <select class="form-control" name="priority">
                            {% for enc, cnc in countrys.items() %}
                            <option value="{{ enc }}">{{ cnc }}</option>
                            {% endfor %}
                        </select>
                    </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
{% endblock %}